export const bookList = [
  "Mateo",
  "Marcos",
  "Lucas",
  "Juan",
  "Mga Gawa",
  "Roma",
  "1 Corinto",
  "2 Corinto",
  "Galacia",
  "Efeso",
  "Filipos",
  "Colosas",
  "1 Tesalonica",
  "2 Tesalonica",
  "1 Timoteo",
  "2 Timoteo",
  "Tito",
  "Filemon",
  "Hebreo",
  "Santiago",
  "1 Pedro",
  "2 Pedro",
  "1 Juan",
  "2 Juan",
  "3 Juan",
  "Judas",
  "Apocalipsis",
];

export const bookListOptions = bookList.map(book => ({ label: book, value: book }));